version: "3"
services:
  nginx:
    restart: always
    container_name: nginx
    image: nginx:latest
    ports:
      # - 8002:8002
      # - 8097:8097
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # nginx 配置文件
      - ./nginx/conf.d:/etc/nginx/conf.d # nginx 配置文件夹
      - ./nginx/logs:/var/log/nginx # nginx 日志映射
      - ./nginx/ssl:/ssl # ssl 证书映射
      - ./index:/index #
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
